// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0XlZ1B1zlfPQvqv9krFf9sDHXaolGlw',
    appId: '1:155170888230:web:8ec6ffb852badcb61d3b0b',
    messagingSenderId: '155170888230',
    projectId: 'jm-imports-2ac55',
    authDomain: 'jm-imports-2ac55.firebaseapp.com',
    storageBucket: 'jm-imports-2ac55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0XlZ1B1zlfPQvqv9krFf9sDHXaolGlw',
    appId: '1:155170888230:android:6f6018f449a012308e24e7',
    messagingSenderId: '155170888230',
    projectId: 'jm-imports-2ac55',
    storageBucket: 'jm-imports-2ac55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY0XlZ1B1zlfPQvqv9krFf9sDHXaolGlw',
    appId: '1:155170888230:ios:50a12b413ac5ce6e1d3b0b',
    messagingSenderId: '155170888230',
    projectId: 'jm-imports-2ac55',
    storageBucket: 'jm-imports-2ac55.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY0XlZ1B1zlfPQvqv9krFf9sDHXaolGlw',
    appId: '1:155170888230:ios:0132332651d147111d3b0b',
    messagingSenderId: '155170888230',
    projectId: 'jm-imports-2ac55',
    storageBucket: 'jm-imports-2ac55.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY0XlZ1B1zlfPQvqv9krFf9sDHXaolGlw',
    appId: '1:155170888230:web:cff1a5697e6b5dfc1d3b0b',
    messagingSenderId: '155170888230',
    projectId: 'jm-imports-2ac55',
    storageBucket: 'jm-imports-2ac55.firebasestorage.app',
  );
}
